name: warnayarra
description: A Dart package to play Snake on your Razer Chroma keyboard.
version: 0.1.0
homepage: https://github.com/Razer-Chroma-Dart/warnayarra.dart

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  razer_chroma_rest_client:
    path: ../razer_chroma/razer_chroma_rest_client
  snake: ^0.1.0

dev_dependencies:
  lint: ^1.8.2
