name: warnayarra_gui
description: A Web app to play Snake on your Razer Chroma keyboard.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  razer_chroma_rest_client:
    path: ../razer_chroma/razer_chroma_rest_client
  warnayarra:
    path: ../warnayarra

dev_dependencies:
  lint: ^1.8.2

flutter:
  uses-material-design: true
